# SPDX-License-Identifier: Apache-2.0
# Fault Analysis of Microscaling Formats on a RISC-V SoC
# Authors: Dillibabu Shanmugam, Patrick Schaumont
# Affiliation: Worcester Polytechnic Institute (WPI), USA

#!/usr/bin/env python3
"""Generate LaTeX tables for MX unified coprocessor fault analysis paper.

Reads CSV results and produces standalone LaTeX table files suitable for
\\input{} inclusion in a paper. All tables use booktabs formatting.

Tables generated:
  1. vulnerability_ranking.tex — 5-way format ranking
  2. per_matrix_breakdown.tex — misclass per weight matrix
  3. bit_sensitivity.tex — bit-position sensitivity
  4. cycle_comparison.tex — SW vs HW coprocessor cycles
  5. resource_utilization.tex — FPGA resource usage
  6. instruction_encoding.tex — MX instruction format table

Usage:
  python3 generate_tables.py results/
  python3 generate_tables.py results/ --output tables/

Authors: Dillibabu Shanmugam, Patrick Schaumont (WPI)
"""

import argparse
import csv
import os
import sys
from collections import defaultdict

# ─────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────

FORMATS = ["mxint8", "mxfp8_e4m3", "mxfp8_e5m2", "mxlog8", "mxlog8_logdom"]

FORMAT_LABELS = {
    "mxint8":        "MXINT8",
    "mxfp8_e4m3":   "MXFP8-E4M3",
    "mxfp8_e5m2":   "MXFP8-E5M2",
    "mxlog8":        "MXLOG8",
    "mxlog8_logdom": "MXLOG8-Logdom",
}

MATRICES = ["W_Q", "W_K", "W_V", "W_L1", "W_L2"]

# Software cycle counts from CAPRI1 attention benchmarks
SW_CYCLES = {
    "mxint8":        9010,
    "mxfp8_e4m3":   10233,
    "mxfp8_e5m2":   10111,
    "mxlog8":        9382,
    "mxlog8_logdom": 8822,
}

# Estimated coprocessor cycle counts
HW_CYCLES_EST = {
    "mxint8":        1800,
    "mxfp8_e4m3":   2000,
    "mxfp8_e5m2":   2000,
    "mxlog8":        1700,
    "mxlog8_logdom": 1500,
}

# Binary sizes (bytes)
BINARY_SIZES = {
    "mxint8":        784,
    "mxfp8_e4m3":   820,
    "mxfp8_e5m2":   820,
    "mxlog8":        840,
    "mxlog8_logdom": 896,
}


# ─────────────────────────────────────────────────────────────────────
# Data loading
# ─────────────────────────────────────────────────────────────────────

def load_results(results_dir):
    """Load all sram_faults_*.csv files."""
    all_data = {}
    for fmt in FORMATS:
        csv_path = os.path.join(results_dir, f"sram_faults_{fmt}.csv")
        if not os.path.exists(csv_path):
            continue
        with open(csv_path, "r") as f:
            all_data[fmt] = list(csv.DictReader(f))
    return all_data


# ─────────────────────────────────────────────────────────────────────
# Table 1: Vulnerability Ranking
# ─────────────────────────────────────────────────────────────────────

def gen_vulnerability_ranking(all_data, output_dir):
    """Generate 5-way vulnerability ranking table."""
    rows = []
    for fmt, data in all_data.items():
        total = len(data)
        misclass = sum(1 for r in data if r["outcome"] == "misclass")
        crash = sum(1 for r in data if r["outcome"] == "crash")
        normal = total - misclass - crash
        vuln_pct = 100.0 * misclass / max(1, total)
        rows.append((fmt, total, misclass, crash, normal, vuln_pct))

    # Sort by vuln_pct ascending (most resilient first)
    rows.sort(key=lambda x: x[5])

    tex = []
    tex.append(r"% Auto-generated by generate_tables.py")
    tex.append(r"\begin{table}[t]")
    tex.append(r"\centering")
    tex.append(r"\caption{5-Way SRAM Fault Vulnerability Ranking — "
               r"Unified MX Coprocessor}")
    tex.append(r"\label{tab:vuln-ranking}")
    tex.append(r"\begin{tabular}{clrrrr}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Rank} & \textbf{Format} & \textbf{Total} & "
               r"\textbf{Misclass} & \textbf{Crash} & \textbf{Vuln\%} \\")
    tex.append(r"\midrule")

    for rank, (fmt, total, misclass, crash, normal, vuln_pct) in enumerate(rows, 1):
        label = FORMAT_LABELS.get(fmt, fmt)
        # Bold the best and worst
        if rank == 1:
            pct_str = r"\textbf{" + f"{vuln_pct:.1f}" + r"\%}"
        elif rank == len(rows):
            pct_str = r"\textbf{" + f"{vuln_pct:.1f}" + r"\%}"
        else:
            pct_str = f"{vuln_pct:.1f}\\%"
        tex.append(f"  {rank} & {label} & {total:,} & {misclass:,} & "
                   f"{crash:,} & {pct_str} \\\\")

    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    path = os.path.join(output_dir, "vulnerability_ranking.tex")
    with open(path, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"  Saved {path}")


# ─────────────────────────────────────────────────────────────────────
# Table 2: Per-Matrix Breakdown
# ─────────────────────────────────────────────────────────────────────

def gen_per_matrix_breakdown(all_data, output_dir):
    """Generate per-matrix misclass breakdown table."""
    tex = []
    tex.append(r"% Auto-generated by generate_tables.py")
    tex.append(r"\begin{table}[t]")
    tex.append(r"\centering")
    tex.append(r"\caption{Per-Matrix Misclassification Breakdown}")
    tex.append(r"\label{tab:per-matrix}")

    n_cols = len(MATRICES)
    col_spec = "l" + "r" * n_cols + "r"
    tex.append(r"\begin{tabular}{" + col_spec + "}")
    tex.append(r"\toprule")

    header = r"\textbf{Format}"
    for mat in MATRICES:
        header += f" & \\textbf{{{mat}}}"
    header += r" & \textbf{Total} \\"
    tex.append(header)
    tex.append(r"\midrule")

    for fmt in FORMATS:
        if fmt not in all_data:
            continue
        label = FORMAT_LABELS.get(fmt, fmt)
        rows = all_data[fmt]
        total_mc = 0
        cells = []
        for mat in MATRICES:
            mat_rows = [r for r in rows if r["matrix"] == mat]
            mc = sum(1 for r in mat_rows if r["outcome"] == "misclass")
            mt = len(mat_rows)
            total_mc += mc
            if mt > 0:
                pct = 100.0 * mc / mt
                if pct > 5:
                    cells.append(r"\textbf{" + f"{mc}/{mt}" + "}")
                else:
                    cells.append(f"{mc}/{mt}")
            else:
                cells.append("---")
        tex.append(f"  {label} & " + " & ".join(cells) + f" & {total_mc} \\\\")

    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    path = os.path.join(output_dir, "per_matrix_breakdown.tex")
    with open(path, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"  Saved {path}")


# ─────────────────────────────────────────────────────────────────────
# Table 3: Bit Sensitivity
# ─────────────────────────────────────────────────────────────────────

def gen_bit_sensitivity(all_data, output_dir):
    """Generate bit-position sensitivity table."""
    tex = []
    tex.append(r"% Auto-generated by generate_tables.py")
    tex.append(r"\begin{table}[t]")
    tex.append(r"\centering")
    tex.append(r"\caption{Bit-Position Sensitivity — Misclassification Rate (\%)}")
    tex.append(r"\label{tab:bit-sensitivity}")
    tex.append(r"\begin{tabular}{l*{8}{r}}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Format} & \textbf{b0} & \textbf{b1} & \textbf{b2} & "
               r"\textbf{b3} & \textbf{b4} & \textbf{b5} & \textbf{b6} & "
               r"\textbf{b7} \\")
    tex.append(r"\midrule")

    for fmt in FORMATS:
        if fmt not in all_data:
            continue
        label = FORMAT_LABELS.get(fmt, fmt)
        rows = all_data[fmt]
        bit_counts = defaultdict(int)
        bit_totals = defaultdict(int)
        for r in rows:
            bit = int(r["bit_in_byte"])
            bit_totals[bit] += 1
            if r["outcome"] == "misclass":
                bit_counts[bit] += 1

        cells = []
        for b in range(8):
            total = bit_totals.get(b, 0)
            mc = bit_counts.get(b, 0)
            if total > 0:
                pct = 100.0 * mc / total
                if pct > 5:
                    cells.append(r"\textbf{" + f"{pct:.1f}" + "}")
                else:
                    cells.append(f"{pct:.1f}")
            else:
                cells.append("---")
        tex.append(f"  {label} & " + " & ".join(cells) + " \\\\")

    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    path = os.path.join(output_dir, "bit_sensitivity.tex")
    with open(path, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"  Saved {path}")


# ─────────────────────────────────────────────────────────────────────
# Table 4: Cycle Comparison (SW vs HW)
# ─────────────────────────────────────────────────────────────────────

def gen_cycle_comparison(output_dir):
    """Generate SW vs HW coprocessor cycle comparison table."""
    tex = []
    tex.append(r"% Auto-generated by generate_tables.py")
    tex.append(r"\begin{table}[t]")
    tex.append(r"\centering")
    tex.append(r"\caption{Attention Workload: Software-Only vs "
               r"Hardware Coprocessor}")
    tex.append(r"\label{tab:cycle-comparison}")
    tex.append(r"\begin{tabular}{lrrrr}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Format} & \textbf{SW Cycles} & "
               r"\textbf{HW Cycles} & \textbf{Speedup} & "
               r"\textbf{Binary} \\")
    tex.append(r"\midrule")

    for fmt in FORMATS:
        label = FORMAT_LABELS.get(fmt, fmt)
        sw = SW_CYCLES.get(fmt, 0)
        hw = HW_CYCLES_EST.get(fmt, 0)
        bsz = BINARY_SIZES.get(fmt, 0)
        speedup = sw / hw if hw > 0 else 0
        tex.append(f"  {label} & {sw:,} & $\\sim${hw:,} & "
                   f"{speedup:.1f}$\\times$ & {bsz}\\,B \\\\")

    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    path = os.path.join(output_dir, "cycle_comparison.tex")
    with open(path, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"  Saved {path}")


# ─────────────────────────────────────────────────────────────────────
# Table 5: FPGA Resource Utilization
# ─────────────────────────────────────────────────────────────────────

def gen_resource_utilization(output_dir):
    """Generate CW305-A100T FPGA resource utilization table."""
    tex = []
    tex.append(r"% Auto-generated by generate_tables.py")
    tex.append(r"\begin{table}[t]")
    tex.append(r"\centering")
    tex.append(r"\caption{CW305-A100T Resource Utilization}")
    tex.append(r"\label{tab:fpga-resources}")
    tex.append(r"\begin{tabular}{lrrr}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Component} & \textbf{LUTs} & \textbf{FFs} & "
               r"\textbf{BRAMs} \\")
    tex.append(r"\midrule")

    resources = [
        ("CVE2 core (RV32IMC)", "~5,000", "~3,000", "0"),
        ("CROC SoC (8KB SRAM, UART)", "~3,000", "~2,000", "4"),
        ("MX coprocessor (unified)", "~4,000", "~500", "1"),
        ("Scan chain (129-bit)", "~200", "~130", "0"),
        ("CW305 glue (BUFGMUX, RTC)", "~200", "~100", "0"),
    ]

    for name, luts, ffs, brams in resources:
        tex.append(f"  {name} & {luts} & {ffs} & {brams} \\\\")

    tex.append(r"\midrule")
    tex.append(r"  \textbf{Total} & \textbf{$\sim$12,400} & "
               r"\textbf{$\sim$5,730} & \textbf{5} \\")
    tex.append(r"  CW305-A100T capacity & 63,400 & 126,800 & 135 \\")
    tex.append(r"  \textbf{Utilization} & \textbf{$\sim$20\%} & "
               r"\textbf{$\sim$5\%} & \textbf{$\sim$4\%} \\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    path = os.path.join(output_dir, "resource_utilization.tex")
    with open(path, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"  Saved {path}")


# ─────────────────────────────────────────────────────────────────────
# Table 6: Instruction Encoding
# ─────────────────────────────────────────────────────────────────────

def gen_instruction_encoding(output_dir):
    """Generate MX instruction encoding table."""
    tex = []
    tex.append(r"% Auto-generated by generate_tables.py")
    tex.append(r"\begin{table}[t]")
    tex.append(r"\centering")
    tex.append(r"\caption{Unified MX Coprocessor Instruction Encoding "
               r"(R-type, opcode=\texttt{0x0B})}")
    tex.append(r"\label{tab:instruction-encoding}")
    tex.append(r"\begin{tabular}{llcc}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Format} & \textbf{Element Type} & "
               r"\textbf{funct7 base} & \textbf{funct7 ext} \\")
    tex.append(r"\midrule")

    encodings = [
        ("MXINT8",        r"1S.7I (two's complement)",      "0x00", "0x01"),
        ("MXFP8-E4M3",   r"1S.4E.3M (bias=7, no Inf)",     "0x04", "0x05"),
        ("MXFP8-E5M2",   r"1S.5E.2M (bias=15, has Inf)",   "0x08", "0x09"),
        ("MXLOG8",        r"1S.4FI.3FE (log, LUT decode)",  "0x0C", "0x0D"),
        ("MXLOG8-Logdom", r"same as MXLOG8 (log-domain dp)","0x10", "0x11"),
    ]

    for name, elem, base, ext in encodings:
        tex.append(f"  {name} & {elem} & "
                   f"\\texttt{{{base}}} & \\texttt{{{ext}}} \\\\")

    tex.append(r"\midrule")
    tex.append(r"\multicolumn{4}{l}{\small Operation = \{funct7[0], funct3\} "
               r"$\rightarrow$ 4-bit selector (16 ops per format)} \\")
    tex.append(r"\multicolumn{4}{l}{\small funct7 = "
               r"\{2'b00, format[2:0], 1'b0, group\}, "
               r"group=0: base, group=1: extended} \\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    path = os.path.join(output_dir, "instruction_encoding.tex")
    with open(path, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"  Saved {path}")


# ─────────────────────────────────────────────────────────────────────
# Table 7: Scan Chain Bit Map
# ─────────────────────────────────────────────────────────────────────

def gen_scan_chain_map(output_dir):
    """Generate scan chain bit map table."""
    tex = []
    tex.append(r"% Auto-generated by generate_tables.py")
    tex.append(r"\begin{table}[t]")
    tex.append(r"\centering")
    tex.append(r"\caption{129-Bit Mux-Scan Chain Observable Signals}")
    tex.append(r"\label{tab:scan-chain}")
    tex.append(r"\begin{tabular}{llr}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Signal} & \textbf{Bits} & \textbf{Width} \\")
    tex.append(r"\midrule")

    signals = [
        (r"\texttt{rs1\_q}",              "128:97", "32"),
        (r"\texttt{rs2\_q}",              "96:65",  "32"),
        (r"\texttt{mac\_acc\_q}",         "64:33",  "32"),
        (r"\texttt{se\_a\_q}",            "32:25",  "8"),
        (r"\texttt{se\_b\_q}",            "24:17",  "8"),
        (r"\texttt{instr\_op\_q}",        "16:13",  "4"),
        (r"\texttt{instr\_fmt\_q}",       "12:10",  "3"),
        (r"\texttt{instr\_inflight\_q}",  "9",      "1"),
        (r"\texttt{instr\_rd\_q}",        "8:4",    "5"),
        (r"\texttt{instr\_id\_q}",        "3:0",    "4"),
    ]

    for sig, bits, width in signals:
        tex.append(f"  {sig} & [{bits}] & {width} \\\\")

    tex.append(r"\midrule")
    tex.append(r"  \textbf{Total} & [128:0] & \textbf{129} \\")
    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    path = os.path.join(output_dir, "scan_chain_map.tex")
    with open(path, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"  Saved {path}")


# ─────────────────────────────────────────────────────────────────────
# Table 8: CAPRI1 vs Unified Coprocessor Comparison
# ─────────────────────────────────────────────────────────────────────

def gen_comparison_table(all_data, output_dir):
    """Compare CAPRI1 (3 separate coprocessors) vs unified architecture."""
    tex = []
    tex.append(r"% Auto-generated by generate_tables.py")
    tex.append(r"\begin{table}[t]")
    tex.append(r"\centering")
    tex.append(r"\caption{Architecture Comparison: Separate vs Unified "
               r"MX Coprocessors}")
    tex.append(r"\label{tab:arch-comparison}")
    tex.append(r"\begin{tabular}{lcc}")
    tex.append(r"\toprule")
    tex.append(r"\textbf{Feature} & \textbf{Separate (3 coproc)} & "
               r"\textbf{Unified (1 coproc)} \\")
    tex.append(r"\midrule")

    comparisons = [
        ("Formats supported",       "3 (INT8, FP8, LOG8)", "5 (all OCP MX)"),
        ("Custom opcodes",          "3 (0x0B, 0x2B, 0x5B)", "1 (0x0B)"),
        ("Shared exponent support", "No",                    "Yes (E8M0)"),
        ("Log-domain dot product",  "No",                    "Yes"),
        ("Estimated LUTs",          "$\\sim$8,000",          "$\\sim$4,000"),
        ("Scan chain bits",         "3 $\\times$ 43",        "129"),
        ("Scan chain signals",      "12 (3 $\\times$ 4)",    "4"),
        ("FPGA target",             "Genesys2",              "CW305-A100T"),
        ("Fault injection",         "SRAM only",             "SRAM + CW glitch"),
    ]

    for feat, sep, uni in comparisons:
        tex.append(f"  {feat} & {sep} & {uni} \\\\")

    tex.append(r"\bottomrule")
    tex.append(r"\end{tabular}")
    tex.append(r"\end{table}")

    path = os.path.join(output_dir, "arch_comparison.tex")
    with open(path, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"  Saved {path}")


# ─────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate LaTeX tables for MX fault analysis paper")
    parser.add_argument("results_dir", nargs="?", default=None,
                        help="Directory containing CSV results (optional)")
    parser.add_argument("--output", default=None,
                        help="Output directory for .tex files")
    args = parser.parse_args()

    if args.output:
        output_dir = args.output
    elif args.results_dir:
        output_dir = os.path.join(args.results_dir, "tables")
    else:
        output_dir = "tables"

    os.makedirs(output_dir, exist_ok=True)

    # Load SRAM results if available
    all_data = {}
    if args.results_dir and os.path.isdir(args.results_dir):
        print("Loading SRAM fault results...")
        all_data = load_results(args.results_dir)

    # Generate tables (some are data-dependent, some are static)
    print("\nGenerating LaTeX tables...")

    if all_data:
        gen_vulnerability_ranking(all_data, output_dir)
        gen_per_matrix_breakdown(all_data, output_dir)
        gen_bit_sensitivity(all_data, output_dir)
        gen_comparison_table(all_data, output_dir)
    else:
        print("  (No SRAM results — skipping data-dependent tables)")

    # Static tables (always generated)
    gen_cycle_comparison(output_dir)
    gen_resource_utilization(output_dir)
    gen_instruction_encoding(output_dir)
    gen_scan_chain_map(output_dir)

    print(f"\nAll tables saved to {output_dir}")


if __name__ == "__main__":
    main()
